/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_lib;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("oh hey");
        return true;
    }
}
